<script setup lang="ts">
import { ArrowLeft, ArrowRight } from "@element-plus/icons-vue";
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { getMangaChapterPages, getManga, getMangaPageBatch, type MangaDetail } from "../../services/manga";
import { saveReadPosition } from "../../services/novel";

const route = useRoute(); const router = useRouter();
const mangaId = computed(() => String(route.params.mangaId)); const chapterId = computed(() => String(route.params.chapterId));
const manga = ref<MangaDetail | null>(null); const pages = ref<string[]>([]); const loading = ref(true); const error = ref(""); const requestedBatches = new Set<number>(); let observer: IntersectionObserver | undefined; let savedPage = -1;
async function loadPage(index: number): Promise<void> { if (pages.value[index]) return; const batchStart = Math.floor(index / 12) * 12; if (requestedBatches.has(batchStart)) return; requestedBatches.add(batchStart); try { const batch = await getMangaPageBatch(chapterId.value, index); batch.pageUrls.forEach((url, offset) => { if (batch.startIndex + offset < pages.value.length) pages.value[batch.startIndex + offset] = url; }); } catch (value) { error.value = typeof value === "string" ? value : "无法加载漫画页面"; } finally { requestedBatches.delete(batchStart); } }
async function load(): Promise<void> { loading.value = true; error.value = ""; requestedBatches.clear(); savedPage = -1; const pagesRequest = getMangaChapterPages(mangaId.value, chapterId.value); const detailRequest = getManga(mangaId.value); try { const list = await pagesRequest; pages.value = Array.from({ length: list.pageCount }, (_, index) => list.firstPageUrls[index] || ""); await nextTick(); observePages(); manga.value = await detailRequest; } catch (value) { error.value = typeof value === "string" ? value : "无法加载漫画页面"; } finally { loading.value = false; } }
function saveProgress(): void { if (!manga.value || savedPage < 0) return; void saveReadPosition(mangaId.value, chapterId.value, String(savedPage + 1)); }
function observePages(): void { observer?.disconnect(); observer = new IntersectionObserver((entries) => { for (const entry of entries) { if (!entry.isIntersecting) continue; const index = Number((entry.target as HTMLElement).dataset.pageIndex); if (!Number.isInteger(index)) continue; void loadPage(index); if (index > savedPage) { savedPage = index; saveProgress(); } } }, { rootMargin: "800px 0px", threshold: 0.01 }); document.querySelectorAll<HTMLElement>(".manga-reader-page").forEach((page) => observer?.observe(page)); }
function chapterOffset(offset: number): void { const chapters = manga.value?.chapters ?? []; const index = chapters.findIndex((chapter) => chapter.id === chapterId.value); const next = chapters[index + offset]; if (next) void router.replace({ name: "manga-reader", params: { mangaId: mangaId.value, chapterId: next.id } }); }
onMounted(() => void load()); onBeforeUnmount(() => { observer?.disconnect(); saveProgress(); });
</script>
<template><article class="manga-reader" v-loading="loading"><header><el-button :icon="ArrowLeft" text @click="router.push({ name: 'manga-detail', params: { mangaId } })">目录</el-button><strong>{{ manga?.title || "漫画阅读" }}</strong><span>{{ pages.length ? `${savedPage + 1} / ${pages.length}` : "" }}</span></header><el-alert v-if="error" type="error" :title="error" show-icon :closable="false" /><p v-else-if="!loading && pages.length === 0" class="manga-reader-pending">正在获取章节页码…</p><template v-for="(page, index) in pages" :key="index"><img v-if="page" class="manga-reader-page" :data-page-index="index" :src="page" :alt="`第 ${index + 1} 页`" /><div v-else class="manga-reader-page manga-reader-page-placeholder" :data-page-index="index">加载第 {{ index + 1 }} 页…</div></template><footer><el-button :icon="ArrowLeft" :disabled="!manga || manga.chapters.findIndex((chapter) => chapter.id === chapterId) <= 0" @click="chapterOffset(-1)">上一话</el-button><el-button :icon="ArrowRight" icon-position="right" :disabled="!manga || manga.chapters.findIndex((chapter) => chapter.id === chapterId) >= manga.chapters.length - 1" @click="chapterOffset(1)">下一话</el-button></footer></article></template>
